### ISSUE TITLE
design contribution

### ISSUE THREAD

**Issue by ihtiht** [fralik/Duorem#12] opened 2018-05-01 22:53 UTC
Hi, I noticed there was no logo of Duorem. This application is really useful and practical. It's also nice to be open source and free.  I want to contribute to Duorem.  That's why I designed a logo. I hope you like it. If you have something you want to change or add, please tell me. And you can choose color. 

![v ew](https://user-images.githubusercontent.com/36369736/39497314-63188abc-4dab-11e8-8e0f-d3fc2a01d58e.jpg)

![viwe](https://user-images.githubusercontent.com/36369736/39497315-67a36f7a-4dab-11e8-8922-c627551ad804.PNG)

![vieww](https://user-images.githubusercontent.com/36369736/39497324-73638c46-4dab-11e8-95af-1d2dded855d2.jpg)

**Comment by fralik** [comment] 2018-05-20 08:46
Hi!
Thank you for the effort! There is actually an [icon](https://github.com/fralik/Duorem/blob/master/app/src/main/res/drawable/ic_launcher.png), which I plan to keep.
The problem is that it is not shown in F-Droid. I am not sure why.

**Comment by ihtiht** [comment] 2018-05-20 11:48
I guess you do not like the design? I can develop design in the direction of requests.

**Comment by fralik** [comment] 2018-05-22 11:13
Yes, I have to be honest. I didn't like it that much. Although I was positively surprised that someone decided to contribute in that direction. Not that the current icon is all that great. I tried to keep two simple elements on it, triangle shapes resemble on and off states and the states are back-ed up by colors. 

If we were to go into details, I think your icon could benefit from small polishing: the vertical line is  closer to the right part of the circle. It fixates the eye on itself too much. The idea behind the icon lies to much on the surface. It's also a bit strange to mock it on an iPhone screen. Duorem is Android only. But again, my thoughts doesn't mean that it is a bad icon, it's more of a personal taste.

I have another open source project, [Rundata-net](https://gitlab.com/fralik/rundata-net), which can benefit from an icon or some design. It has an icon already, but I guess it can be improved or different variants created. If not an icon, then the project needs CSS polishing, so that the whole thing looks better.

**Comment by ihtiht** [comment] 2018-05-23 18:49
My goal is only to contribute to open source projects. I did not understand clearly how you liked the design I made. That's why I wanted to ask. He noticed some mistakes because he was in the development stage of the design. Anyway, I will continue contributing to open source projects. I will do something at the right time for the rundata-net.  Thank you for your interest. 

Good work!

**Comment by fralik** [comment] 2018-05-26 08:48
It's a great goal!
Rundata-net is open sourced as you probably saw. In my opinion it might have more value for community than Duorem, but I do not really know how many people out there use Duorem.

I am closing the issue now.

**Closed as completed by fralik** 2018-05-26 08:48 UTC
