### ISSUE TITLE
Synology NAS shuts down only by second try

### ISSUE THREAD

**Issue by just-Nob** [fralik/Duorem#2] opened 2017-06-10 13:56 UTC
Hi,

this is really a nice piece of work! :-)
I like the possibility to shut down my Synology NAS remotely.

It works ___nearly___ without problems together with my Synology NAS Station, except one problem:

To shut down the NAS, it needs always _two_ times before the NAS shuts down.

Maybe this is a timing problem?

**Comment by fralik** [comment] 2017-06-14 20:56
Hi!
Could you try to SSH to your NAS and issue 'sudo poweroff' command? What will be the outcome?
I think that I saw such behaviour during testing with my machine, but it happened with 'shutdown -h' command. That is why I use 'poweroff' now.

**Comment by fralik** [comment] 2017-06-16 12:32
I think that I found the cause and fixed it. Can you build an app from master and see that it works for you? I can make a release after this.

**Comment by just-Nob** [comment] 2017-06-17 11:17
Hi @fralik,

thanks foryour reply!

Unfortunately, I neither have the toolchain installed on my PC, nor I have the experience to build up an Android app. :( 
Wanted to learn Android / java programming, but hadn't had the time until now. I registered here at Github for posting bug reports, as well as a German translation of some apps' resource files, perhaps. ;) 

I wanted to contact you per pm for giving you an eMail address, so that you could send me a compiled test build. Unfortunately, there doesn't seem to be a possibility in Github for pms. :( 
I could try to build the app, but this is just a matter of time (which is really spare at the moment), our do you know a way for pms in Github?

Best regards
Nob

**Comment by fralik** [comment] 2017-06-17 16:01
I see. Here is a link to test APK:
[duorem-v1.1.0-debug.zip](https://github.com/fralik/Duorem/files/1082631/duorem-v1.1.0-debug.zip)

As for pms on GitHub. I think it doesn't support them. I once looked for it as well.

**Comment by just-Nob** [comment] 2017-06-17 20:04
Thx... - this seems tofix the problem. :) 
As I noticed, there's an additional parameter at the "advanced" section to give a custom shutdown string (don't know if that was given in v. 1.0 as well), but I didn't changed the default "sudo shutdown -h now".

**Comment by fralik** [comment] 2017-06-18 16:09
Good! I close the issue than. It will be part of version 1.1.0.

Ability to customise shutdown command was not in the initial version. I thought that the issue your saw with your NAS was related to the particular shutdown command I was using (not the case). So, I've added this option. I think that It can still be useful. And in a way it provides an opportunity to type in any command and execute it via shutdown button.

**Closed as completed by fralik** 2017-06-18 16:09 UTC
Labels: bug

**Comment by just-Nob** [comment] 2017-06-19 05:28
I'll keep an eye on it, but how that the issue it's gone.
Anyway, a good idea to make this editable!
